name: CI

on:
  pull_request:
    branches: "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dpependencies
        run: yarn --pure-lockfile
      
      - name: Build
        run: yarn build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}
           
      - name: Set Tags
        id: set_tags
        run: |
          if [ $GITHUB_REF == 'refs/heads/master' ]
          then 
            echo "::set-output name=ghcr::ghcr.io/khu-dev/khumu-frontend:production"
          else
            echo "::set-output name=ghcr::ghcr.io/khu-dev/khumu-frontend:test"
          fi
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ steps.set_tags.outputs.ghcr }}
            labels:  org.opencontainers.image.source=https://github.com/khu-dev/khumu-frontend