name: CI
on:
  push:
    branches: [ dev, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dpependencies
        run: yarn --pure-lockfile

      - name: copy env
        if: github.ref == 'refs/heads/dev'
        run: cp -rf .env.test .env.production
      
      - name: Build
        run: yarn build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ steps.set_tags.outputs.ghcr }}
            labels:  org.opencontainers.image.source=https://github.com/khu-dev/khumu-frontend